# Generated by Django 3.0.6 on 2020-07-06 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IFRSData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('ccf_over', models.FloatField(null=True)),
                ('lgd_auto', models.FloatField(null=True)),
                ('lgd_nedv', models.FloatField(null=True)),
                ('lgd_potr', models.FloatField(null=True)),
                ('lgd_delay', models.FloatField(null=True)),
                ('lgd_over', models.FloatField(null=True)),
                ('pd_auto_0', models.FloatField(null=True)),
                ('pd_auto_1_30', models.FloatField(null=True)),
                ('pd_auto_31_60', models.FloatField(null=True)),
                ('pd_auto_61_90', models.FloatField(null=True)),
                ('pd_auto_91', models.FloatField(null=True)),
                ('pd_nedv_0', models.FloatField(null=True)),
                ('pd_nedv_1_30', models.FloatField(null=True)),
                ('pd_nedv_31_60', models.FloatField(null=True)),
                ('pd_nedv_61_90', models.FloatField(null=True)),
                ('pd_nedv_91', models.FloatField(null=True)),
                ('pd_potr_0', models.FloatField(null=True)),
                ('pd_potr_1_30', models.FloatField(null=True)),
                ('pd_potr_31_60', models.FloatField(null=True)),
                ('pd_potr_61_90', models.FloatField(null=True)),
                ('pd_potr_91', models.FloatField(null=True)),
                ('pd_delay_0', models.FloatField(null=True)),
                ('pd_delay_1_30', models.FloatField(null=True)),
                ('pd_delay_31_60', models.FloatField(null=True)),
                ('pd_delay_61_90', models.FloatField(null=True)),
                ('pd_delay_91', models.FloatField(null=True)),
                ('pd_over_0', models.FloatField(null=True)),
                ('pd_over_1_30', models.FloatField(null=True)),
                ('pd_over_31_60', models.FloatField(null=True)),
                ('pd_over_61_90', models.FloatField(null=True)),
                ('pd_over_91', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_name', models.CharField(default=None, max_length=255)),
                ('table_size', models.CharField(default=None, max_length=255)),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(default=None, max_length=255)),
                ('file_type', models.CharField(default=None, max_length=255)),
                ('file_date', models.DateField()),
                ('uploading_time', models.TimeField()),
            ],
        ),
    ]
